"""add fundamentals tables and price provenance

Revision ID: 711eb02dd360
Revises: 3db3d1192154
Create Date: 2026-09-25 17:35:09.114460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "711eb02dd360"
down_revision: str | Sequence[str] | None = "3db3d1192154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_fundamentals_current",
        sa.Column("stock_id", sa.UUID(), nullable=False),
        sa.Column("statement_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_assets", sa.Numeric(), nullable=True),
        sa.Column("current_liabilities", sa.Numeric(), nullable=True),
        sa.Column("inventory", sa.Numeric(), nullable=True),
        sa.Column("shareholders_equity", sa.Numeric(), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(), nullable=True),
        sa.Column("net_income", sa.Numeric(), nullable=True),
        sa.Column("revenue", sa.Numeric(), nullable=True),
        sa.Column("previous_year_revenue", sa.Numeric(), nullable=True),
        sa.Column("operating_profit_after_tax", sa.Numeric(), nullable=True),
        sa.Column("invested_capital", sa.Numeric(), nullable=True),
        sa.Column("cash_from_operations", sa.Numeric(), nullable=True),
        sa.Column("capex", sa.Numeric(), nullable=True),
        sa.Column("dividend_per_share", sa.Numeric(), nullable=True),
        sa.Column("eps", sa.Numeric(), nullable=True),
        sa.Column("data_source", sa.String(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("source_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_successful_refresh_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("stock_id"),
    )
    op.create_table(
        "stock_fundamentals_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stock_id", sa.UUID(), nullable=False),
        sa.Column("statement_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_assets", sa.Numeric(), nullable=True),
        sa.Column("current_liabilities", sa.Numeric(), nullable=True),
        sa.Column("inventory", sa.Numeric(), nullable=True),
        sa.Column("shareholders_equity", sa.Numeric(), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(), nullable=True),
        sa.Column("net_income", sa.Numeric(), nullable=True),
        sa.Column("revenue", sa.Numeric(), nullable=True),
        sa.Column("previous_year_revenue", sa.Numeric(), nullable=True),
        sa.Column("operating_profit_after_tax", sa.Numeric(), nullable=True),
        sa.Column("invested_capital", sa.Numeric(), nullable=True),
        sa.Column("cash_from_operations", sa.Numeric(), nullable=True),
        sa.Column("capex", sa.Numeric(), nullable=True),
        sa.Column("dividend_per_share", sa.Numeric(), nullable=True),
        sa.Column("eps", sa.Numeric(), nullable=True),
        sa.Column("data_source", sa.String(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("source_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stock_fundamentals_history_stock_id_recorded_at",
        "stock_fundamentals_history",
        ["stock_id", "recorded_at"],
        unique=False,
    )
    op.add_column("stock_prices_current", sa.Column("data_source", sa.String(), nullable=False))
    op.add_column("stock_prices_current", sa.Column("needs_review", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_prices_current", "needs_review")
    op.drop_column("stock_prices_current", "data_source")
    op.drop_index(
        "ix_stock_fundamentals_history_stock_id_recorded_at",
        table_name="stock_fundamentals_history",
    )
    op.drop_table("stock_fundamentals_history")
    op.drop_table("stock_fundamentals_current")
    # ### end Alembic commands ###
