/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market Overview
         * @description Bucket and sector filtered, offset-paginated, cache-aside
         *     against Redis with the versioned key pattern from
         *     docs/backend-architecture/02.md: a miss falls back to Postgres,
         *     already fast given the indexing in 01.md, then populates the
         *     cache. Only already-scored stocks show up here, per 01.md's
         *     "market overview reads already-computed rows" rule, no scoring
         *     happens on this request path.
         */
        get: operations["market_overview_api_v1_markets__market__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_api_v1_stocks__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ticker}/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Price History
         * @description What the price chart (Frontend Phase 5) actually renders from,
         *     per 01.md's price_history/stock_prices_current split: append-only,
         *     one row per successful refresh cycle for this stock. Not part of
         *     the original Phase 4 read-API list, added once the chart's real
         *     prerequisite (an endpoint exposing this table at all) turned out
         *     not to exist yet, the same kind of real, necessary gap as the
         *     has_session cookie caught in an earlier phase.
         */
        get: operations["stock_price_history_api_v1_stocks__ticker__price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Typo-tolerant trigram search over ticker and company name, per
         *     01.md: "zenit" still finds Zenith Bank. Ranked by whichever of the
         *     two columns matches better, not summed, so a strong ticker match
         *     doesn't get out-ranked by a weak name match added on top of it.
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description No new storage, per 01.md: fetches each stock's already-cached
         *     detail read and computes the best-in-comparison highlight at
         *     render time. Best is judged by percentile, the same number
         *     already shown on the page for each metric, since the scoring
         *     pipeline itself has no separate notion of a metric's "good"
         *     direction beyond a higher sector-relative percentile.
         */
        get: operations["compare_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favorites
         * @description The authenticated user's own list, a direct indexed Postgres
         *     read, deliberately not cached, per 02.md: already fast, already
         *     per-user, real invalidation cost for no real benefit.
         */
        get: operations["list_favorites_api_v1_favorites_get"];
        put?: never;
        /** Add Favorite */
        post: operations["add_favorite_api_v1_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Favorite */
        delete: operations["remove_favorite_api_v1_favorites__stock_id__delete"];
        options?: never;
        head?: never;
        /** Update Favorite Status */
        patch: operations["update_favorite_status_api_v1_favorites__stock_id__patch"];
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Not named in Sub-phase 6.1's task list (only POST and DELETE
         *     are), added for the same reason Favorites got a GET: a resource
         *     with no way to read it back isn't usable, and this mirrors the
         *     exact shape app/api/v1/favorites.py already established.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_v1_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Sub-phase 10.4: a soft delete, not a hard DELETE, per docs/
         *     backend-architecture/02.md, sets deleted_at and anonymizes the
         *     users row's personal fields, leaves subscriptions and
         *     payment_events untouched (likely needed for accounting purposes
         *     regardless of what a user asked deleted about their own profile).
         *     The exact retention period before an anonymized row is ever purged
         *     for good is a real, still-open NDPR question, per 02.md's explicit
         *     instruction not to guess at it here; this endpoint is the request
         *     mechanism, correct regardless of what that period turns out to be.
         *
         *     A hijacked session cookie alone can't trigger this: the current
         *     password is required too, the same extra confirmation change-
         *     password already asks for, since this action can't be undone by
         *     logging back in the way a password change can.
         */
        delete: operations["delete_account_api_v1_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Share
         * @description Snapshots the caller's favorites list as it exists right now,
         *     per 01_product.md: "here's what I'm watching right now," not a
         *     live view that would keep drifting for the 24 hours the link
         *     stays valid. No Postgres row, per 02.md, this data is inherently
         *     disposable and doesn't need to survive a service restart the way
         *     a user's actual account data does.
         */
        post: operations["create_share_api_v1_share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share
         * @description Unauthenticated on purpose, per 01_product.md: anyone with the
         *     link can view it, no login needed on their end. Rate-limited per
         *     IP against enumeration, per Sub-phase 7.2, since a token is the
         *     only thing standing between a guess and someone else's favorites
         *     list. A missing key reads as 404 whether it never existed or
         *     already expired, Redis has already deleted it either way, no
         *     separate expiry check needed.
         */
        get: operations["get_share_api_v1_share__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["create_checkout_api_v1_subscriptions_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entitlement
         * @description A plain yes/no, not part of Backend Phase 6/7/8's original task
         *     list: Frontend Sub-phase 8.2 needs to know which empty state to
         *     show (free-tier Lock icon vs. the real paid-tier form) before any
         *     gated action is attempted, and require_feature() alone only
         *     answers that by way of a 402 after the fact.
         */
        get: operations["get_entitlement_api_v1_subscriptions_entitlement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/paystack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paystack Webhook */
        post: operations["paystack_webhook_api_v1_webhooks_paystack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/flutterwave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flutterwave Webhook */
        post: operations["flutterwave_webhook_api_v1_webhooks_flutterwave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description What a load balancer polls, per docs/backend-architecture/00.md's
         *     availability section: confirms the process is actually serving
         *     requests, not just that it's running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFavoriteRequest */
        AddFavoriteRequest: {
            /** Ticker */
            ticker: string;
            /** Market */
            market: string;
        };
        /** AlertRule */
        AlertRule: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Rule Type */
            rule_type: string;
            /** Rule Config */
            rule_config: {
                [key: string]: unknown;
            };
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AlertsResponse */
        AlertsResponse: {
            /** Items */
            items: components["schemas"]["AlertRule"][];
        };
        /** CategoryBlock */
        CategoryBlock: {
            /** Category */
            category: string;
            /** Score */
            score: number | null;
            /** Metrics */
            metrics: components["schemas"]["MetricValue"][];
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Provider */
            provider: string;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Redirect Url */
            redirect_url: string;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Stocks */
            stocks: components["schemas"]["StockDetailResponse"][];
            /** Best In Comparison */
            best_in_comparison: {
                [key: string]: string;
            };
        };
        /** CreateAlertRequest */
        CreateAlertRequest: {
            /** Ticker */
            ticker: string;
            /** Market */
            market: string;
            /** Rule Type */
            rule_type: string;
            /**
             * Rule Config
             * @default {}
             */
            rule_config: {
                [key: string]: unknown;
            };
        };
        /** CreateShareResponse */
        CreateShareResponse: {
            /** Token */
            token: string;
            /** Share Url */
            share_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** EntitlementResponse */
        EntitlementResponse: {
            /** Entitled */
            entitled: boolean;
        };
        /** FavoriteItem */
        FavoriteItem: {
            /**
             * Stock Id
             * Format: uuid
             */
            stock_id: string;
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Sector */
            sector: string;
            /** Status */
            status: string;
            /** Price */
            price: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Bucket */
            bucket: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FavoritesResponse */
        FavoritesResponse: {
            /** Items */
            items: components["schemas"]["FavoriteItem"][];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** GlossaryPayloadEntry */
        GlossaryPayloadEntry: {
            /** Term */
            term: string;
            /** Short Definition */
            short_definition: string;
            /** Slug */
            slug: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Status */
            status: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MetricValue */
        MetricValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /** Percentile */
            percentile: number | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Items */
            items: components["schemas"]["StockSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PriceHistoryResponse */
        PriceHistoryResponse: {
            /** Items */
            items: components["schemas"]["PricePoint"][];
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Price */
            price: number;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Items */
            items: components["schemas"]["SearchResultItem"][];
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Sector */
            sector: string;
        };
        /** ShareSnapshotItem */
        ShareSnapshotItem: {
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Sector */
            sector: string;
            /** Status */
            status: string;
            /** Price */
            price: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Bucket */
            bucket: string | null;
        };
        /** ShareView */
        ShareView: {
            /** Items */
            items: components["schemas"]["ShareSnapshotItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Terms Version */
            terms_version: string;
            /**
             * Turnstile Token
             * @default
             */
            turnstile_token: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Verified */
            verified: boolean;
        };
        /** StockDetailResponse */
        StockDetailResponse: {
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Sector */
            sector: string;
            /** Price */
            price: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Bucket */
            bucket: string | null;
            /** Categories */
            categories: components["schemas"]["CategoryBlock"][];
            /** Explanation */
            explanation: string;
            /** Glossary */
            glossary: {
                [key: string]: components["schemas"]["GlossaryPayloadEntry"];
            };
            /** News */
            news: {
                [key: string]: unknown;
            }[];
            /** Scores As Of */
            scores_as_of: string | null;
            /** Price As Of */
            price_as_of: string | null;
            /** Fundamentals As Of */
            fundamentals_as_of: string | null;
        };
        /** StockSummary */
        StockSummary: {
            /** Ticker */
            ticker: string;
            /** Company Name */
            company_name: string;
            /** Market */
            market: string;
            /** Sector */
            sector: string;
            /** Price */
            price: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Bucket */
            bucket: string | null;
            /** Last Successful Refresh At */
            last_successful_refresh_at: string | null;
        };
        /** UpdateFavoriteStatusRequest */
        UpdateFavoriteStatusRequest: {
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_overview_api_v1_markets__market__overview_get: {
        parameters: {
            query?: {
                sector?: string | null;
                bucket?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_api_v1_stocks__ticker__get: {
        parameters: {
            query?: {
                market?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_price_history_api_v1_stocks__ticker__price_history_get: {
        parameters: {
            query?: {
                market?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_compare_get: {
        parameters: {
            query: {
                /** @description Comma-separated tickers, 2 or 3 */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_v1_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
        };
    };
    add_favorite_api_v1_favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_v1_favorites__stock_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_favorite_status_api_v1_favorites__stock_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFavoriteStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_v1_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_api_v1_share_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateShareResponse"];
                };
            };
        };
    };
    get_share_api_v1_share__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_api_v1_subscriptions_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entitlement_api_v1_subscriptions_entitlement_get: {
        parameters: {
            query: {
                feature: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paystack_webhook_api_v1_webhooks_paystack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    flutterwave_webhook_api_v1_webhooks_flutterwave_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
